### ISSUE TITLE
Doc site search doesn't show `std.Regex` documentation when I search for the term "regex"

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#4400]
### I tried this:

1. https://www.winglang.io/docs/
2. Searched for "regex" via the searchbox on top right.

### This happened:

4 search result items appeared, none of them was the reference doc for `std.Regex` (https://www.winglang.io/docs/standard-library/regex/api-reference).

### I expected this:

To see the reference docs as the first option

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by skorfmann** [comment]
See this Slack [thread](https://winglang.slack.com/archives/C048QCN2XLJ/p1697533243059069) as well

**Comment by ainvoner** [comment]
fixed Algolia search. There was an index blocker due to some major docs changes.

**Comment by skorfmann** [comment]
> fixed Algolia search. There was an index blocker due to some major docs changes.

Still doesn't seem to find [Libraries](https://www.winglang.io/docs/libraries) when searching for `Libraries`.

**Comment by ainvoner** [comment]
@skorfmann can you please try again. The libraries example is now working for me

**Comment by staycoolcall911** [comment]
It didn't work for me either yesterday, but it does now. I guess we can drop it.

**Comment by skorfmann** [comment]
> @skorfmann can you please try again. The libraries example is now working for me

Yes, works now - thanks!
