### ISSUE TITLE
Doc site search changes the browser url. Navigating to that url leads to http 404

### ISSUE THREAD

**Issue by staycoolcall911** [winglang/wing#4401]
### I tried this:

1. https://winglang.io/docs/
2. Searched for "regex" via the searchbox on top right.
3. Clicked "See all 4 results" at the bottom part of the quick-results panel
![image](https://github.com/winglang/wing/assets/106860404/0c18d0d4-5a81-4ed1-a656-4d8f115bb72d)

### This happened:

Browser address bar navigated to this url: https://www.winglang.io/search?q=regex which leads to an http 404 page (not found) if I refresh the browser or click on that link.

### I expected this:

Stable, bookmarkable navigation.

### Component

Documentation

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by ainvoner** [comment]
see if `searchPagePath` in `docusaurus.config.js` should be changed to `docs/search`

**Comment by Chriscbr** [comment]
The page that's linked (https://www.winglang.io/search?q=regex) appears to show a list of valid search results now, so it looks like this was fixed.

**Comment by staycoolcall911** [comment]
Still doesn't work for me.
![image](https://github.com/winglang/wing/assets/106860404/b4d10e01-9faf-4847-bec2-89b2c753279c)

**Comment by Chriscbr** [comment]
Odd -- yeah it seems when I open the link directly it doesn't work, but if I go through the UI (type in search bar, scroll down inside the modal and click "See all results" at the bottom) then I'm taken to the page with the full results, and the page has the same URL (screenshot below) 🤔 

<img width="1276" alt="Screenshot 2023-12-20 at 2 02 17 PM" src="https://github.com/winglang/wing/assets/5008987/2608dcd1-3e24-414a-afe3-61f497fc9f26">

**Comment by garysassano** [comment]
I find that using the search bar on the docsite works for me, but directly going to [winglang.io/search?q=regex](https://www.winglang.io/search?q=regex) does not, leading me to believe the problem lies in how the server handles requests with query parameters.

![image](https://github.com/winglang/wing/assets/10464497/ab93f70e-d5b6-4054-bbd6-553afdfa7870)

**Comment by garysassano** [comment]
I think it may be related to [this](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/).

**Comment by garysassano** [comment]
I think you need to set `routing: true` in InstantSearch.js, as explained [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/).

**Comment by garysassano** [comment]
I think you need to set `routing: true` in InstantSearch, as explained [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/).

**Comment by garysassano** [comment]
I think you need to set `routing` to `true` in InstantSearch, as explained [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/).

**Comment by staycoolcall911** [comment]
Still happens when I refresh the results page: https://www.winglang.io/search?q=regex
